### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by ryanramage** [ssbc/patchwork-electron#1]
Was playing around with this, tried the instructions but i got this

```
 git:(master) ®[patchwork-electron]$ npm start

> @ start /Users/ryan/rtemp/patchwork-electron
> node ./tasks/start

Module version mismatch. Expected 47, got 46.
[CFG] Password: NO.
[CFG] TLS: NO.
[CFG] Remote Access: NO.
Starting...
Module version mismatch. Expected 47, got 46.
App threw an error when running [Error: Module version mismatch. Expected 47, got 46.]
/Users/ryan/rtemp/patchwork/node_modules/ssb-keys/node_modules/chloride/node_modules/sodium-browserify/node_modules/libsodium-wrappers/node_modules/libsodium/dist/modules/libsodium.js:14
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["

Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:162:18)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:162:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at bindings (/Users/ryan/rtemp/patchwork/node_modules/scuttlebot/node_modules/secure-scuttlebutt/node_modules/level/node_modules/leveldown/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/ryan/rtemp/patchwork/node_modules/scuttlebot/node_modules/secure-scuttlebutt/node_modules/level/node_modules/leveldown/leveldown.js:4:46)
```

**Comment by pfrazee** [comment]
Make sure you use node 5.x

**Comment by ryanramage** [comment]
Ah thx.
