### ISSUE TITLE
copy link id is broken

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork-electron#4]
I get this error:

``` js
Error: prompt() is and will not be supported.
    at window.prompt (/home/dominic/c/patchwork-electron/node_modules/electron-prebuilt/dist/resources/atom.asar/renderer/lib/override.js:164:9)
    at Card.copyLink (http://localhost:7777/main.build.js:53:11523)
    at Card.onSelectDropdown (http://localhost:7777/main.build.js:53:11252)
    at DropdownBtn.onSelect (http://localhost:7777/main.build.js:48:11155)
    at http://localhost:7777/main.build.js:48:10219
    at Object.invokeGuardedCallback (http://localhost:7777/main.build.js:38:2360)
    at executeDispatch (http://localhost:7777/main.build.js:33:2518)
    at Object.executeDispatchesInOrder (http://localhost:7777/main.build.js:33:2908)
    at executeDispatchesAndRelease (http://localhost:7777/main.build.js:32:23139)
    at executeDispatchesAndReleaseTopLevel (http://localhost:7777/main.build.js:32:23399)
```

I'd kinda rather just see the link, maybe?

**Comment by pfrazee** [comment]
We've already got this logged at https://github.com/ssbc/patchwork/issues/284
